In [1]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.11-cp311-cp311-macosx_11_0_arm64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 7.1 MB/s  0:00:00 eta 0:00:01m
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
import psycopg2

conn = psycopg2.connect(host="localhost",
                        database= "Stock_database",
                        user="postgres",
                        password="1234",
                        port="5432")

In [4]:
cur = conn.cursor()

In [7]:
import sys
import os

# Add project root to path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
sys.path.insert(0, project_root)

from backend_handlers.record_feeders.news.final_accumulator import build_news_dataframe

In [ ]:
company_slug = "reliance-industries"

df = build_news_dataframe(company_slug=company_slug, keywords=["reliance", "jio", "ril"], ticker="RELIANCE.NS")

Scraping page 1 - found 8 articles
Scraping page 2 - found 26 articles
Scraping page 3 - found 26 articles
Total collected: 7
Fetched 1 entries from Moneycontrol
Fetched 50 entries from Economic Times
Fetched 35 entries from LiveMint
Fetched 0 entries from Business Standard

In [14]:
df["company"] = company_slug

In [15]:
df.head()

,title,url,source,published,scraped_at,company
7,Reliance Industries Ltd stock (INE002A01018): ...,https://news.google.com/rss/articles/CBMiuwFBV...,Google News,"Wed, 15 Apr 2026 20:58:00 GMT",2026-04-18T21:00:32.416960,reliance-industries
34,Dividend Stock 2026: Reliance Industries-backe...,https://news.google.com/rss/articles/CBMi9AFBV...,Google News,"Wed, 15 Apr 2026 15:04:59 GMT",2026-04-18T21:00:34.157680,reliance-industries
32,India Stocks Soar: Global Optimism Lifts Marke...,https://news.google.com/rss/articles/CBMi0AFBV...,Google News,"Wed, 15 Apr 2026 03:59:09 GMT",2026-04-18T21:00:34.157676,reliance-industries
35,PPFAS Portfolio Churn: Rajeev Thakkar-led fund...,https://news.google.com/rss/articles/CBMilgJBV...,Google News,"Thu, 16 Apr 2026 09:40:49 GMT",2026-04-18T21:00:34.157682,reliance-industries
8,"Reliance Industries shares slump nearly 4%, ma...",https://news.google.com/rss/articles/CBMi5wFBV...,Google News,"Sun, 05 Apr 2026 07:00:00 GMT",2026-04-18T21:00:32.416963,reliance-industries

In [20]:
import pandas as pd

df["date"] = pd.to_datetime(
    df["published"],
    format="mixed",     # handles multiple formats
    errors="coerce",    # avoids crashes
    utc=True            # standardize timezone
)

# Extract year, month, day
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

df.head()

,title,url,source,published,scraped_at,company,date,year,month,day
7,Reliance Industries Ltd stock (INE002A01018): ...,https://news.google.com/rss/articles/CBMiuwFBV...,Google News,"Wed, 15 Apr 2026 20:58:00 GMT",2026-04-18T21:00:32.416960,reliance-industries,2026-04-15 20:58:00+00:00,2026,4,15
34,Dividend Stock 2026: Reliance Industries-backe...,https://news.google.com/rss/articles/CBMi9AFBV...,Google News,"Wed, 15 Apr 2026 15:04:59 GMT",2026-04-18T21:00:34.157680,reliance-industries,2026-04-15 15:04:59+00:00,2026,4,15
32,India Stocks Soar: Global Optimism Lifts Marke...,https://news.google.com/rss/articles/CBMi0AFBV...,Google News,"Wed, 15 Apr 2026 03:59:09 GMT",2026-04-18T21:00:34.157676,reliance-industries,2026-04-15 03:59:09+00:00,2026,4,15
35,PPFAS Portfolio Churn: Rajeev Thakkar-led fund...,https://news.google.com/rss/articles/CBMilgJBV...,Google News,"Thu, 16 Apr 2026 09:40:49 GMT",2026-04-18T21:00:34.157682,reliance-industries,2026-04-16 09:40:49+00:00,2026,4,16
8,"Reliance Industries shares slump nearly 4%, ma...",https://news.google.com/rss/articles/CBMi5wFBV...,Google News,"Sun, 05 Apr 2026 07:00:00 GMT",2026-04-18T21:00:32.416963,reliance-industries,2026-04-05 07:00:00+00:00,2026,4,5

In [21]:
df_final = df[["company", "title", "url", "year", "month", "day"]]

In [23]:
df_final.head()

,company,title,url,year,month,day
7,reliance-industries,Reliance Industries Ltd stock (INE002A01018): ...,https://news.google.com/rss/articles/CBMiuwFBV...,2026,4,15
34,reliance-industries,Dividend Stock 2026: Reliance Industries-backe...,https://news.google.com/rss/articles/CBMi9AFBV...,2026,4,15
32,reliance-industries,India Stocks Soar: Global Optimism Lifts Marke...,https://news.google.com/rss/articles/CBMi0AFBV...,2026,4,15
35,reliance-industries,PPFAS Portfolio Churn: Rajeev Thakkar-led fund...,https://news.google.com/rss/articles/CBMilgJBV...,2026,4,16
8,reliance-industries,"Reliance Industries shares slump nearly 4%, ma...",https://news.google.com/rss/articles/CBMi5wFBV...,2026,4,5

In [24]:
cur.execute("""
            CREATE TABLE IF NOT EXISTS news (
                id SERIAL PRIMARY KEY,
                company VARCHAR(255),
                title TEXT,
                url TEXT,
                year INT,
                month INT,
                day INT
            )
            """)

In [ ]:
### Test transcripts

In [ ]:
from backend_handlers.record_feeders.transcripts.get_nse_filings import get_nse_filings
from backend_handlers.record_feeders.transcripts.extract_documents import extract_documents
filings_df = get_nse_filings("RELIANCE")
docs = extract_documents(filings_df)

In [32]:
data = docs  # your dictionary

filtered_data = {
    key: [item for item in value if item.get("url") and item.get("url") != "-"]
    for key, value in data.items()
}

In [39]:
data_cons = [filtered_data["transcript"][-1]] + filtered_data["results"][:3]

In [40]:
data_cons

[{'title': 'Transcript of Analysts/Institutional Investor Meet/Con. Call',
  'url': 'https://nsearchives.nseindia.com/corporate/RELIANCE_07052022113222_AVRecordingandTranscript.pdf'},
 {'title': 'Financial Result Updates',
  'url': 'https://nsearchives.nseindia.com/corporate/SE_Result_16012025192542.pdf'},
 {'title': 'Financial Result Updates',
  'url': 'https://nsearchives.nseindia.com/corporate/BM_SE_14102024190232.pdf'},
 {'title': 'Financial Result Updates',
  'url': 'https://nsearchives.nseindia.com/corporate/SEFR_19072024191604.pdf'}]

In [41]:
df_transcripts = pd.DataFrame(data_cons)

In [42]:
df_transcripts

,title,url
0,Transcript of Analysts/Institutional Investor ...,https://nsearchives.nseindia.com/corporate/REL...
1,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SE_...
2,Financial Result Updates,https://nsearchives.nseindia.com/corporate/BM_...
3,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SEF...

In [43]:
df_transcripts["company"] = "RELIANCE"

In [44]:
df_transcripts

,title,url,company
0,Transcript of Analysts/Institutional Investor ...,https://nsearchives.nseindia.com/corporate/REL...,RELIANCE
1,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SE_...,RELIANCE
2,Financial Result Updates,https://nsearchives.nseindia.com/corporate/BM_...,RELIANCE
3,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SEF...,RELIANCE

In [ ]:
from backend_handlers.record_feeders.transcripts.get_pdf import download_pdf

In [2]:
from backend_handlers.record_feeders.transcripts.transcript_final_executor import process_transcripts

df_transcripts_final = process_transcripts("RELIANCE")

Saved: transcripts/Con. Call_2026-04-19_1.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_2.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_3.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_4.pdf

In [3]:
df_transcripts_final.head()

,title,url,filepath,symbol,date
0,Transcript of Analysts/Institutional Investor ...,https://nsearchives.nseindia.com/corporate/REL...,transcripts//Con. Call_2026-04-19_1.pdf,RELIANCE,2026-04-19
1,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SE_...,transcripts//RELIANCE_Financial Result Updates...,RELIANCE,2026-04-19
2,Financial Result Updates,https://nsearchives.nseindia.com/corporate/BM_...,transcripts//RELIANCE_Financial Result Updates...,RELIANCE,2026-04-19
3,Financial Result Updates,https://nsearchives.nseindia.com/corporate/SEF...,transcripts//RELIANCE_Financial Result Updates...,RELIANCE,2026-04-19

In [ ]:
cur.execute("""
            CREATE TABLE IF NOT EXISTS transcripts_2 (
                id SERIAL PRIMARY KEY,
                company VARCHAR(255),
                title TEXT,
                url TEXT,
                filepath TEXT,
                date DATE
            )
            """)

In [ ]:

import requests
import time
url = f"https://www.nseindia.com/api/equity-stockIndices?index=NIFTY%20IT"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.nseindia.com/",
}

session = requests.Session()
session.headers.update(headers)

for attempt in range(2):
    # Visit homepage first to establish session and get cookies
    home_response = session.get(
        "https://www.nseindia.com", 
    )
    print(home_response.status_code)
    
    # Longer delay to ensure cookies are set
    time.sleep(1.5)

    # Fetch the actual index data
    response = session.get(url)
    response.raise_for_status()

    data = response.json()

200
{'name': 'NIFTY IT', 'advance': {'declines': '3', 'advances': '7', 'unchanged': '0'}, 'timestamp': '17-Apr-2026 16:00:00', 'data': [{'priority': 1, 'symbol': 'NIFTY IT', 'identifier': 'NIFTY IT', 'open': 31656.55, 'dayHigh': 31959.35, 'dayLow': 31411.75, 'lastPrice': 31809.85, 'previousClose': 31817.5, 'change': -7.650000000001455, 'pChange': -0.02, 'ffmc': 122894437.05, 'yearHigh': 40301.4, 'yearLow': 28288.05, 'totalTradedVolume': 105098944, 'stockIndClosePrice': 0, 'totalTradedValue': 59213985135.75, 'lastUpdateTime': '17-Apr-2026 16:00:00', 'nearWKH': 21.07011170827813, 'nearWKL': -12.449780030790386, 'perChange365d': -4.68, 'perChange30d': 10.6, 'date365dAgo': '16-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/NIFTY-IT.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/NIFTY-IT.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/NIFTY-IT.svg'}, {'priority': 0, 'symbol': 'WIPRO', 'identifier': 'WIPROEQN', 'series': 'EQ', 'open': 205, 'dayHigh': 206.45, 'dayLow': 202.5, 'lastPrice': 204.3, 'previousClose': 210.26, 'change': -5.96, 'pChange': -2.83, 'totalTradedVolume': 80542603, 'stockIndClosePrice': 0, 'totalTradedValue': 16460491775.11, 'yearHigh': 273.1, 'ffmc': 582227597618.46, 'yearLow': 186.5, 'nearWKH': 25.19223727572318, 'nearWKL': -9.544235924932982, 'perChange365d': -13.76, 'perChange30d': 6.78, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/WIPROEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/WIPRO-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/WIPRO-EQ.svg', 'meta': {'symbol': 'WIPRO', 'companyName': 'Wipro Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE075A01022', 'slb_isin': 'INE075A01022', 'listingDate': '1995-11-08', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'INFY', 'identifier': 'INFYEQN', 'series': 'EQ', 'open': 1313, 'dayHigh': 1328.3, 'dayLow': 1306.1, 'lastPrice': 1320, 'previousClose': 1319.2, 'change': 0.8, 'pChange': 0.06, 'totalTradedVolume': 12064048, 'stockIndClosePrice': 0, 'totalTradedValue': 15860965827.04, 'yearHigh': 1728, 'ffmc': 4615357157378.92, 'yearLow': 1215.1, 'nearWKH': 23.61111111111111, 'nearWKL': -8.633034318163123, 'perChange365d': -7.01, 'perChange30d': 7.06, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/INFYEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/INFY-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/INFY-EQ.svg', 'meta': {'symbol': 'INFY', 'companyName': 'Infosys Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE009A01021', 'slb_isin': 'INE009A01021', 'listingDate': '1995-02-08', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'TCS', 'identifier': 'TCSEQN', 'series': 'EQ', 'open': 2570, 'dayHigh': 2589, 'dayLow': 2555.9, 'lastPrice': 2583.6, 'previousClose': 2576.9, 'change': 6.7, 'pChange': 0.26, 'totalTradedVolume': 2718206, 'stockIndClosePrice': 0, 'totalTradedValue': 7007453521.82, 'yearHigh': 3630.5, 'ffmc': 2630926302424.85, 'yearLow': 2346.2, 'nearWKH': 28.83624845062664, 'nearWKL': -10.118489472338252, 'perChange365d': -21.68, 'perChange30d': 8.02, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/TCSEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/TCS-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/TCS-EQ.svg', 'meta': {'symbol': 'TCS', 'companyName': 'Tata Consultancy Services Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE467B01029', 'slb_isin': 'INE467B01029', 'listingDate': '2004-08-25', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'HCLTECH', 'identifier': 'HCLTECHEQN', 'series': 'EQ', 'open': 1443.3, 'dayHigh': 1458, 'dayLow': 1430, 'lastPrice': 1443, 'previousClose': 1450.2, 'change': -7.2, 'pChange': -0.5, 'totalTradedVolume': 3319268, 'stockIndClosePrice': 0, 'totalTradedValue': 4774036779.04, 'yearHigh': 1780.1, 'ffmc': 1518464441031.29, 'yearLow': 1297.7, 'nearWKH': 18.93713836301331, 'nearWKL': -11.196732680896968, 'perChange365d': 0.35, 'perChange30d': 9.23, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/HCLTECHEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/HCLTECH-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/HCLTECH-EQ.svg', 'meta': {'symbol': 'HCLTECH', 'companyName': 'HCL Technologies Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE860A01027', 'slb_isin': 'INE860A01027', 'listingDate': '2000-01-06', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'PERSISTENT', 'identifier': 'PERSISTENTEQN', 'series': 'EQ', 'open': 5470, 'dayHigh': 5505, 'dayLow': 5380.3, 'lastPrice': 5443, 'previousClose': 5500.5, 'change': -57.5, 'pChange': -1.05, 'totalTradedVolume': 841855, 'stockIndClosePrice': 0, 'totalTradedValue': 4576525825.2, 'yearHigh': 6599, 'ffmc': 590548200785.25, 'yearLow': 4449.1, 'nearWKH': 17.517805728140626, 'nearWKL': -22.339349531365887, 'perChange365d': 12.55, 'perChange30d': 20.17, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/PERSISTENTEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/PERSISTENT-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/PERSISTENT-EQ.svg', 'meta': {'symbol': 'PERSISTENT', 'companyName': 'Persistent Systems Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': ['IL'], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE262H01021', 'slb_isin': 'INE262H01021', 'listingDate': '2010-04-06', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'COFORGE', 'identifier': 'COFORGEEQN', 'series': 'EQ', 'open': 1310, 'dayHigh': 1329, 'dayLow': 1293.3, 'lastPrice': 1317.9, 'previousClose': 1313.2, 'change': 4.7, 'pChange': 0.36, 'totalTradedVolume': 2822554, 'stockIndClosePrice': 0, 'totalTradedValue': 3707960964.26, 'yearHigh': 1994, 'ffmc': 441406598090.02, 'yearLow': 1008.1, 'nearWKH': 33.906720160481434, 'nearWKL': -30.731078266045042, 'perChange365d': -0.16, 'perChange30d': 22.72, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/COFORGEEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/COFORGE-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/COFORGE-EQ.svg', 'meta': {'symbol': 'COFORGE', 'companyName': 'Coforge Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE591G01025', 'slb_isin': 'INE591G01025', 'listingDate': '2004-08-30', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'TECHM', 'identifier': 'TECHMEQN', 'series': 'EQ', 'open': 1486, 'dayHigh': 1522.5, 'dayLow': 1474.9, 'lastPrice': 1512.3, 'previousClose': 1491, 'change': 21.3, 'pChange': 1.43, 'totalTradedVolume': 1859402, 'stockIndClosePrice': 0, 'totalTradedValue': 2805911994.08, 'yearHigh': 1854, 'ffmc': 957456286129.85, 'yearLow': 1275.9, 'nearWKH': 18.430420711974115, 'nearWKL': -18.52809781330824, 'perChange365d': 15.73, 'perChange30d': 12.71, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/TECHMEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/TECHM-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/TECHM-EQ.svg', 'meta': {'symbol': 'TECHM', 'companyName': 'Tech Mahindra Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE669C01036', 'slb_isin': 'INE669C01036', 'listingDate': '2006-08-28', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'LTM', 'identifier': 'LTMEQN', 'series': 'EQ', 'open': 4724.9, 'dayHigh': 4778.9, 'dayLow': 4644.2, 'lastPrice': 4740, 'previousClose': 4730, 'change': 10, 'pChange': 0.21, 'totalTradedVolume': 339240, 'stockIndClosePrice': 0, 'totalTradedValue': 1607963676, 'yearHigh': 6429.5, 'ffmc': 438579229801.07, 'yearLow': 4000, 'nearWKH': 26.277315498872387, 'nearWKL': -18.5, 'perChange365d': 13.08, 'perChange30d': 13.15, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/LTMEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/LTM-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/LTM-EQ.svg', 'meta': {'symbol': 'LTM', 'companyName': 'LTM Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ', 'T0'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE214T01019', 'slb_isin': 'INE214T01019', 'listingDate': '2016-07-21', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'OFSS', 'identifier': 'OFSSEQN', 'series': 'EQ', 'open': 7795, 'dayHigh': 8020, 'dayLow': 7716, 'lastPrice': 8001.5, 'previousClose': 7776, 'change': 225.5, 'pChange': 2.9, 'totalTradedVolume': 175320, 'stockIndClosePrice': 0, 'totalTradedValue': 1392522930, 'yearHigh': 9950, 'ffmc': 190104353891.78, 'yearLow': 6234.5, 'nearWKH': 19.582914572864322, 'nearWKL': -28.342288876413505, 'perChange365d': 0.65, 'perChange30d': 26.97, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/OFSSEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/OFSS-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/OFSS-EQ.svg', 'meta': {'symbol': 'OFSS', 'companyName': 'Oracle Financial Services Software Limited', 'industry': 'Software Products', 'activeSeries': ['EQ'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE881D01027', 'slb_isin': 'INE881D01027', 'listingDate': '2002-06-28', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}, {'priority': 0, 'symbol': 'MPHASIS', 'identifier': 'MPHASISEQN', 'series': 'EQ', 'open': 2435, 'dayHigh': 2468.2, 'dayLow': 2402.5, 'lastPrice': 2458.1, 'previousClose': 2441.8, 'change': 16.3, 'pChange': 0.67, 'totalTradedVolume': 416448, 'stockIndClosePrice': 0, 'totalTradedValue': 1020151843.2, 'yearHigh': 3037.2, 'ffmc': 324373537664.92, 'yearLow': 2013, 'nearWKH': 19.06690372711708, 'nearWKL': -22.111276701440634, 'perChange365d': 8.11, 'perChange30d': 18.51, 'date365dAgo': '17-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/MPHASISEQN.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/MPHASIS-EQ.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/MPHASIS-EQ.svg', 'meta': {'symbol': 'MPHASIS', 'companyName': 'MphasiS Limited', 'industry': 'Computers - Software & Consulting', 'activeSeries': ['EQ'], 'debtSeries': [], 'isFNOSec': True, 'isCASec': False, 'isSLBSec': True, 'isDebtSec': False, 'isSuspended': False, 'tempSuspendedSeries': [], 'isETFSec': False, 'isDelisted': False, 'isin': 'INE356A01018', 'slb_isin': 'INE356A01018', 'listingDate': '2004-06-04', 'isMunicipalBond': False, 'isHybridSymbol': False, 'segment': 'EQUITY', 'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00', 'preOpenTime': '17-Apr-2026 09:07:31', 'QuotePreOpenFlag': False}}}], 'metadata': {'indexName': 'NIFTY IT', 'open': 31656.55, 'high': 31959.35, 'low': 31411.75, 'previousClose': 31817.5, 'last': 31809.85, 'percChange': -0.02, 'change': -7.650000000001455, 'timeVal': '17-Apr-2026 21:00:30', 'yearHigh': 40301.4, 'yearLow': 28288.05, 'indicativeClose': 0, 'perChange365d': -4.68, 'perChange30d': 10.6, 'date365dAgo': '16-Apr-2025', 'date30dAgo': '17-Mar-2026', 'chartTodayPath': 'https://nsearchives.nseindia.com/today/NIFTY-IT.svg', 'chart30dPath': 'https://nsearchives.nseindia.com/30d/NIFTY-IT.svg', 'chart365dPath': 'https://nsearchives.nseindia.com/365d/NIFTY-IT.svg', 'totalTradedVolume': 105098944, 'totalTradedValue': 59213985135.75, 'ffmc_sum': 122894437.05}, 'marketStatus': {'market': 'Capital Market', 'marketStatus': 'Close', 'tradeDate': '17-Apr-2026 15:30', 'index': 'NIFTY 50', 'last': 24353.55, 'variation': 156.79999999999927, 'percentChange': 0.65, 'marketStatusMessage': 'Normal Market is Closed'}}
200

In [68]:
data["data"]

[{'priority': 1,
  'symbol': 'NIFTY IT',
  'identifier': 'NIFTY IT',
  'open': 31656.55,
  'dayHigh': 31959.35,
  'dayLow': 31411.75,
  'lastPrice': 31809.85,
  'previousClose': 31817.5,
  'change': -7.650000000001455,
  'pChange': -0.02,
  'ffmc': 122894437.05,
  'yearHigh': 40301.4,
  'yearLow': 28288.05,
  'totalTradedVolume': 105098944,
  'stockIndClosePrice': 0,
  'totalTradedValue': 59213985135.75,
  'lastUpdateTime': '17-Apr-2026 16:00:00',
  'nearWKH': 21.07011170827813,
  'nearWKL': -12.449780030790386,
  'perChange365d': -4.68,
  'perChange30d': 10.6,
  'date365dAgo': '16-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/NIFTY-IT.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/NIFTY-IT.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/NIFTY-IT.svg'},
 {'priority': 0,
  'symbol': 'WIPRO',
  'identifier': 'WIPROEQN',
  'series': 'EQ',
  'open': 205,
  'dayHigh': 206.45,
  'dayLow': 202.5,
  'lastPrice': 204.3,
  'previousClose': 210.26,
  'change': -5.96,
  'pChange': -2.83,
  'totalTradedVolume': 80542603,
  'stockIndClosePrice': 0,
  'totalTradedValue': 16460491775.11,
  'yearHigh': 273.1,
  'ffmc': 582227597618.46,
  'yearLow': 186.5,
  'nearWKH': 25.19223727572318,
  'nearWKL': -9.544235924932982,
  'perChange365d': -13.76,
  'perChange30d': 6.78,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/WIPROEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/WIPRO-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/WIPRO-EQ.svg',
  'meta': {'symbol': 'WIPRO',
   'companyName': 'Wipro Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE075A01022',
   'slb_isin': 'INE075A01022',
   'listingDate': '1995-11-08',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'INFY',
  'identifier': 'INFYEQN',
  'series': 'EQ',
  'open': 1313,
  'dayHigh': 1328.3,
  'dayLow': 1306.1,
  'lastPrice': 1320,
  'previousClose': 1319.2,
  'change': 0.8,
  'pChange': 0.06,
  'totalTradedVolume': 12064048,
  'stockIndClosePrice': 0,
  'totalTradedValue': 15860965827.04,
  'yearHigh': 1728,
  'ffmc': 4615357157378.92,
  'yearLow': 1215.1,
  'nearWKH': 23.61111111111111,
  'nearWKL': -8.633034318163123,
  'perChange365d': -7.01,
  'perChange30d': 7.06,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/INFYEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/INFY-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/INFY-EQ.svg',
  'meta': {'symbol': 'INFY',
   'companyName': 'Infosys Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE009A01021',
   'slb_isin': 'INE009A01021',
   'listingDate': '1995-02-08',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'TCS',
  'identifier': 'TCSEQN',
  'series': 'EQ',
  'open': 2570,
  'dayHigh': 2589,
  'dayLow': 2555.9,
  'lastPrice': 2583.6,
  'previousClose': 2576.9,
  'change': 6.7,
  'pChange': 0.26,
  'totalTradedVolume': 2718206,
  'stockIndClosePrice': 0,
  'totalTradedValue': 7007453521.82,
  'yearHigh': 3630.5,
  'ffmc': 2630926302424.85,
  'yearLow': 2346.2,
  'nearWKH': 28.83624845062664,
  'nearWKL': -10.118489472338252,
  'perChange365d': -21.68,
  'perChange30d': 8.02,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/TCSEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/TCS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/TCS-EQ.svg',
  'meta': {'symbol': 'TCS',
   'companyName': 'Tata Consultancy Services Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE467B01029',
   'slb_isin': 'INE467B01029',
   'listingDate': '2004-08-25',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'HCLTECH',
  'identifier': 'HCLTECHEQN',
  'series': 'EQ',
  'open': 1443.3,
  'dayHigh': 1458,
  'dayLow': 1430,
  'lastPrice': 1443,
  'previousClose': 1450.2,
  'change': -7.2,
  'pChange': -0.5,
  'totalTradedVolume': 3319268,
  'stockIndClosePrice': 0,
  'totalTradedValue': 4774036779.04,
  'yearHigh': 1780.1,
  'ffmc': 1518464441031.29,
  'yearLow': 1297.7,
  'nearWKH': 18.93713836301331,
  'nearWKL': -11.196732680896968,
  'perChange365d': 0.35,
  'perChange30d': 9.23,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/HCLTECHEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/HCLTECH-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/HCLTECH-EQ.svg',
  'meta': {'symbol': 'HCLTECH',
   'companyName': 'HCL Technologies Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE860A01027',
   'slb_isin': 'INE860A01027',
   'listingDate': '2000-01-06',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'PERSISTENT',
  'identifier': 'PERSISTENTEQN',
  'series': 'EQ',
  'open': 5470,
  'dayHigh': 5505,
  'dayLow': 5380.3,
  'lastPrice': 5443,
  'previousClose': 5500.5,
  'change': -57.5,
  'pChange': -1.05,
  'totalTradedVolume': 841855,
  'stockIndClosePrice': 0,
  'totalTradedValue': 4576525825.2,
  'yearHigh': 6599,
  'ffmc': 590548200785.25,
  'yearLow': 4449.1,
  'nearWKH': 17.517805728140626,
  'nearWKL': -22.339349531365887,
  'perChange365d': 12.55,
  'perChange30d': 20.17,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/PERSISTENTEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/PERSISTENT-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/PERSISTENT-EQ.svg',
  'meta': {'symbol': 'PERSISTENT',
   'companyName': 'Persistent Systems Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': ['IL'],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE262H01021',
   'slb_isin': 'INE262H01021',
   'listingDate': '2010-04-06',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'COFORGE',
  'identifier': 'COFORGEEQN',
  'series': 'EQ',
  'open': 1310,
  'dayHigh': 1329,
  'dayLow': 1293.3,
  'lastPrice': 1317.9,
  'previousClose': 1313.2,
  'change': 4.7,
  'pChange': 0.36,
  'totalTradedVolume': 2822554,
  'stockIndClosePrice': 0,
  'totalTradedValue': 3707960964.26,
  'yearHigh': 1994,
  'ffmc': 441406598090.02,
  'yearLow': 1008.1,
  'nearWKH': 33.906720160481434,
  'nearWKL': -30.731078266045042,
  'perChange365d': -0.16,
  'perChange30d': 22.72,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/COFORGEEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/COFORGE-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/COFORGE-EQ.svg',
  'meta': {'symbol': 'COFORGE',
   'companyName': 'Coforge Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE591G01025',
   'slb_isin': 'INE591G01025',
   'listingDate': '2004-08-30',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'TECHM',
  'identifier': 'TECHMEQN',
  'series': 'EQ',
  'open': 1486,
  'dayHigh': 1522.5,
  'dayLow': 1474.9,
  'lastPrice': 1512.3,
  'previousClose': 1491,
  'change': 21.3,
  'pChange': 1.43,
  'totalTradedVolume': 1859402,
  'stockIndClosePrice': 0,
  'totalTradedValue': 2805911994.08,
  'yearHigh': 1854,
  'ffmc': 957456286129.85,
  'yearLow': 1275.9,
  'nearWKH': 18.430420711974115,
  'nearWKL': -18.52809781330824,
  'perChange365d': 15.73,
  'perChange30d': 12.71,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/TECHMEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/TECHM-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/TECHM-EQ.svg',
  'meta': {'symbol': 'TECHM',
   'companyName': 'Tech Mahindra Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE669C01036',
   'slb_isin': 'INE669C01036',
   'listingDate': '2006-08-28',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'LTM',
  'identifier': 'LTMEQN',
  'series': 'EQ',
  'open': 4724.9,
  'dayHigh': 4778.9,
  'dayLow': 4644.2,
  'lastPrice': 4740,
  'previousClose': 4730,
  'change': 10,
  'pChange': 0.21,
  'totalTradedVolume': 339240,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1607963676,
  'yearHigh': 6429.5,
  'ffmc': 438579229801.07,
  'yearLow': 4000,
  'nearWKH': 26.277315498872387,
  'nearWKL': -18.5,
  'perChange365d': 13.08,
  'perChange30d': 13.15,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/LTMEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/LTM-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/LTM-EQ.svg',
  'meta': {'symbol': 'LTM',
   'companyName': 'LTM Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE214T01019',
   'slb_isin': 'INE214T01019',
   'listingDate': '2016-07-21',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'OFSS',
  'identifier': 'OFSSEQN',
  'series': 'EQ',
  'open': 7795,
  'dayHigh': 8020,
  'dayLow': 7716,
  'lastPrice': 8001.5,
  'previousClose': 7776,
  'change': 225.5,
  'pChange': 2.9,
  'totalTradedVolume': 175320,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1392522930,
  'yearHigh': 9950,
  'ffmc': 190104353891.78,
  'yearLow': 6234.5,
  'nearWKH': 19.582914572864322,
  'nearWKL': -28.342288876413505,
  'perChange365d': 0.65,
  'perChange30d': 26.97,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/OFSSEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/OFSS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/OFSS-EQ.svg',
  'meta': {'symbol': 'OFSS',
   'companyName': 'Oracle Financial Services Software Limited',
   'industry': 'Software Products',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE881D01027',
   'slb_isin': 'INE881D01027',
   'listingDate': '2002-06-28',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'MPHASIS',
  'identifier': 'MPHASISEQN',
  'series': 'EQ',
  'open': 2435,
  'dayHigh': 2468.2,
  'dayLow': 2402.5,
  'lastPrice': 2458.1,
  'previousClose': 2441.8,
  'change': 16.3,
  'pChange': 0.67,
  'totalTradedVolume': 416448,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1020151843.2,
  'yearHigh': 3037.2,
  'ffmc': 324373537664.92,
  'yearLow': 2013,
  'nearWKH': 19.06690372711708,
  'nearWKL': -22.111276701440634,
  'perChange365d': 8.11,
  'perChange30d': 18.51,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/MPHASISEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/MPHASIS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/MPHASIS-EQ.svg',
  'meta': {'symbol': 'MPHASIS',
   'companyName': 'MphasiS Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE356A01018',
   'slb_isin': 'INE356A01018',
   'listingDate': '2004-06-04',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}}]

In [72]:


df = pd.DataFrame(data["data"])

# ✅ Remove index row (priority = 1)
df = df[df["priority"] == 0]

# ✅ Keep only required columns safely
required_cols = ["symbol", "lastPrice", "pChange"]
df = df[[col for col in required_cols if col in df.columns]]


# ✅ Convert to numeric (important for sorting)
df["pChange"] = pd.to_numeric(df["pChange"], errors="coerce")
df["lastPrice"] = pd.to_numeric(df["lastPrice"], errors="coerce")

# Drop NaNs just in case
df = df.dropna(subset=["pChange", "lastPrice"])

# ✅ Get top gainers
gainers = (
    df.sort_values("pChange", ascending=False)
      .head(3)
      .reset_index(drop=True)
)

In [74]:
from backend_handlers.record_feeders.market_positions.fetch_nse_index_gainers import fetch_nse_index

fetch_nse_index("NIFTY%20IT")

200

[{'priority': 1,
  'symbol': 'NIFTY IT',
  'identifier': 'NIFTY IT',
  'open': 31656.55,
  'dayHigh': 31959.35,
  'dayLow': 31411.75,
  'lastPrice': 31809.85,
  'previousClose': 31817.5,
  'change': -7.650000000001455,
  'pChange': -0.02,
  'ffmc': 122894437.05,
  'yearHigh': 40301.4,
  'yearLow': 28288.05,
  'totalTradedVolume': 105098944,
  'stockIndClosePrice': 0,
  'totalTradedValue': 59213985135.75,
  'lastUpdateTime': '17-Apr-2026 16:00:00',
  'nearWKH': 21.07011170827813,
  'nearWKL': -12.449780030790386,
  'perChange365d': -4.68,
  'perChange30d': 10.6,
  'date365dAgo': '16-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/NIFTY-IT.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/NIFTY-IT.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/NIFTY-IT.svg'},
 {'priority': 0,
  'symbol': 'WIPRO',
  'identifier': 'WIPROEQN',
  'series': 'EQ',
  'open': 205,
  'dayHigh': 206.45,
  'dayLow': 202.5,
  'lastPrice': 204.3,
  'previousClose': 210.26,
  'change': -5.96,
  'pChange': -2.83,
  'totalTradedVolume': 80542603,
  'stockIndClosePrice': 0,
  'totalTradedValue': 16460491775.11,
  'yearHigh': 273.1,
  'ffmc': 582227597618.46,
  'yearLow': 186.5,
  'nearWKH': 25.19223727572318,
  'nearWKL': -9.544235924932982,
  'perChange365d': -13.76,
  'perChange30d': 6.78,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/WIPROEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/WIPRO-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/WIPRO-EQ.svg',
  'meta': {'symbol': 'WIPRO',
   'companyName': 'Wipro Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE075A01022',
   'slb_isin': 'INE075A01022',
   'listingDate': '1995-11-08',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'INFY',
  'identifier': 'INFYEQN',
  'series': 'EQ',
  'open': 1313,
  'dayHigh': 1328.3,
  'dayLow': 1306.1,
  'lastPrice': 1320,
  'previousClose': 1319.2,
  'change': 0.8,
  'pChange': 0.06,
  'totalTradedVolume': 12064048,
  'stockIndClosePrice': 0,
  'totalTradedValue': 15860965827.04,
  'yearHigh': 1728,
  'ffmc': 4615357157378.92,
  'yearLow': 1215.1,
  'nearWKH': 23.61111111111111,
  'nearWKL': -8.633034318163123,
  'perChange365d': -7.01,
  'perChange30d': 7.06,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/INFYEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/INFY-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/INFY-EQ.svg',
  'meta': {'symbol': 'INFY',
   'companyName': 'Infosys Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE009A01021',
   'slb_isin': 'INE009A01021',
   'listingDate': '1995-02-08',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'TCS',
  'identifier': 'TCSEQN',
  'series': 'EQ',
  'open': 2570,
  'dayHigh': 2589,
  'dayLow': 2555.9,
  'lastPrice': 2583.6,
  'previousClose': 2576.9,
  'change': 6.7,
  'pChange': 0.26,
  'totalTradedVolume': 2718206,
  'stockIndClosePrice': 0,
  'totalTradedValue': 7007453521.82,
  'yearHigh': 3630.5,
  'ffmc': 2630926302424.85,
  'yearLow': 2346.2,
  'nearWKH': 28.83624845062664,
  'nearWKL': -10.118489472338252,
  'perChange365d': -21.68,
  'perChange30d': 8.02,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/TCSEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/TCS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/TCS-EQ.svg',
  'meta': {'symbol': 'TCS',
   'companyName': 'Tata Consultancy Services Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE467B01029',
   'slb_isin': 'INE467B01029',
   'listingDate': '2004-08-25',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'HCLTECH',
  'identifier': 'HCLTECHEQN',
  'series': 'EQ',
  'open': 1443.3,
  'dayHigh': 1458,
  'dayLow': 1430,
  'lastPrice': 1443,
  'previousClose': 1450.2,
  'change': -7.2,
  'pChange': -0.5,
  'totalTradedVolume': 3319268,
  'stockIndClosePrice': 0,
  'totalTradedValue': 4774036779.04,
  'yearHigh': 1780.1,
  'ffmc': 1518464441031.29,
  'yearLow': 1297.7,
  'nearWKH': 18.93713836301331,
  'nearWKL': -11.196732680896968,
  'perChange365d': 0.35,
  'perChange30d': 9.23,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/HCLTECHEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/HCLTECH-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/HCLTECH-EQ.svg',
  'meta': {'symbol': 'HCLTECH',
   'companyName': 'HCL Technologies Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE860A01027',
   'slb_isin': 'INE860A01027',
   'listingDate': '2000-01-06',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'PERSISTENT',
  'identifier': 'PERSISTENTEQN',
  'series': 'EQ',
  'open': 5470,
  'dayHigh': 5505,
  'dayLow': 5380.3,
  'lastPrice': 5443,
  'previousClose': 5500.5,
  'change': -57.5,
  'pChange': -1.05,
  'totalTradedVolume': 841855,
  'stockIndClosePrice': 0,
  'totalTradedValue': 4576525825.2,
  'yearHigh': 6599,
  'ffmc': 590548200785.25,
  'yearLow': 4449.1,
  'nearWKH': 17.517805728140626,
  'nearWKL': -22.339349531365887,
  'perChange365d': 12.55,
  'perChange30d': 20.17,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/PERSISTENTEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/PERSISTENT-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/PERSISTENT-EQ.svg',
  'meta': {'symbol': 'PERSISTENT',
   'companyName': 'Persistent Systems Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': ['IL'],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE262H01021',
   'slb_isin': 'INE262H01021',
   'listingDate': '2010-04-06',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'COFORGE',
  'identifier': 'COFORGEEQN',
  'series': 'EQ',
  'open': 1310,
  'dayHigh': 1329,
  'dayLow': 1293.3,
  'lastPrice': 1317.9,
  'previousClose': 1313.2,
  'change': 4.7,
  'pChange': 0.36,
  'totalTradedVolume': 2822554,
  'stockIndClosePrice': 0,
  'totalTradedValue': 3707960964.26,
  'yearHigh': 1994,
  'ffmc': 441406598090.02,
  'yearLow': 1008.1,
  'nearWKH': 33.906720160481434,
  'nearWKL': -30.731078266045042,
  'perChange365d': -0.16,
  'perChange30d': 22.72,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/COFORGEEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/COFORGE-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/COFORGE-EQ.svg',
  'meta': {'symbol': 'COFORGE',
   'companyName': 'Coforge Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE591G01025',
   'slb_isin': 'INE591G01025',
   'listingDate': '2004-08-30',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'TECHM',
  'identifier': 'TECHMEQN',
  'series': 'EQ',
  'open': 1486,
  'dayHigh': 1522.5,
  'dayLow': 1474.9,
  'lastPrice': 1512.3,
  'previousClose': 1491,
  'change': 21.3,
  'pChange': 1.43,
  'totalTradedVolume': 1859402,
  'stockIndClosePrice': 0,
  'totalTradedValue': 2805911994.08,
  'yearHigh': 1854,
  'ffmc': 957456286129.85,
  'yearLow': 1275.9,
  'nearWKH': 18.430420711974115,
  'nearWKL': -18.52809781330824,
  'perChange365d': 15.73,
  'perChange30d': 12.71,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/TECHMEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/TECHM-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/TECHM-EQ.svg',
  'meta': {'symbol': 'TECHM',
   'companyName': 'Tech Mahindra Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE669C01036',
   'slb_isin': 'INE669C01036',
   'listingDate': '2006-08-28',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'LTM',
  'identifier': 'LTMEQN',
  'series': 'EQ',
  'open': 4724.9,
  'dayHigh': 4778.9,
  'dayLow': 4644.2,
  'lastPrice': 4740,
  'previousClose': 4730,
  'change': 10,
  'pChange': 0.21,
  'totalTradedVolume': 339240,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1607963676,
  'yearHigh': 6429.5,
  'ffmc': 438579229801.07,
  'yearLow': 4000,
  'nearWKH': 26.277315498872387,
  'nearWKL': -18.5,
  'perChange365d': 13.08,
  'perChange30d': 13.15,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/LTMEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/LTM-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/LTM-EQ.svg',
  'meta': {'symbol': 'LTM',
   'companyName': 'LTM Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ', 'T0'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE214T01019',
   'slb_isin': 'INE214T01019',
   'listingDate': '2016-07-21',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'OFSS',
  'identifier': 'OFSSEQN',
  'series': 'EQ',
  'open': 7795,
  'dayHigh': 8020,
  'dayLow': 7716,
  'lastPrice': 8001.5,
  'previousClose': 7776,
  'change': 225.5,
  'pChange': 2.9,
  'totalTradedVolume': 175320,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1392522930,
  'yearHigh': 9950,
  'ffmc': 190104353891.78,
  'yearLow': 6234.5,
  'nearWKH': 19.582914572864322,
  'nearWKL': -28.342288876413505,
  'perChange365d': 0.65,
  'perChange30d': 26.97,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/OFSSEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/OFSS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/OFSS-EQ.svg',
  'meta': {'symbol': 'OFSS',
   'companyName': 'Oracle Financial Services Software Limited',
   'industry': 'Software Products',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE881D01027',
   'slb_isin': 'INE881D01027',
   'listingDate': '2002-06-28',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}},
 {'priority': 0,
  'symbol': 'MPHASIS',
  'identifier': 'MPHASISEQN',
  'series': 'EQ',
  'open': 2435,
  'dayHigh': 2468.2,
  'dayLow': 2402.5,
  'lastPrice': 2458.1,
  'previousClose': 2441.8,
  'change': 16.3,
  'pChange': 0.67,
  'totalTradedVolume': 416448,
  'stockIndClosePrice': 0,
  'totalTradedValue': 1020151843.2,
  'yearHigh': 3037.2,
  'ffmc': 324373537664.92,
  'yearLow': 2013,
  'nearWKH': 19.06690372711708,
  'nearWKL': -22.111276701440634,
  'perChange365d': 8.11,
  'perChange30d': 18.51,
  'date365dAgo': '17-Apr-2025',
  'date30dAgo': '17-Mar-2026',
  'chartTodayPath': 'https://nsearchives.nseindia.com/today/MPHASISEQN.svg',
  'chart30dPath': 'https://nsearchives.nseindia.com/30d/MPHASIS-EQ.svg',
  'chart365dPath': 'https://nsearchives.nseindia.com/365d/MPHASIS-EQ.svg',
  'meta': {'symbol': 'MPHASIS',
   'companyName': 'MphasiS Limited',
   'industry': 'Computers - Software & Consulting',
   'activeSeries': ['EQ'],
   'debtSeries': [],
   'isFNOSec': True,
   'isCASec': False,
   'isSLBSec': True,
   'isDebtSec': False,
   'isSuspended': False,
   'tempSuspendedSeries': [],
   'isETFSec': False,
   'isDelisted': False,
   'isin': 'INE356A01018',
   'slb_isin': 'INE356A01018',
   'listingDate': '2004-06-04',
   'isMunicipalBond': False,
   'isHybridSymbol': False,
   'segment': 'EQUITY',
   'quotepreopenstatus': {'equityTime': '17-Apr-2026 16:00:00',
    'preOpenTime': '17-Apr-2026 09:07:31',
    'QuotePreOpenFlag': False}}}]

In [3]:
from backend_handlers.record_feeders.market_positions.top_gainers_in_sector_nse import top_gainers_in_sector

top_gainers_in_sector("NIFTY%20IT")

200

        index   symbol  pChange
0  NIFTY%20IT     OFSS     2.90
1  NIFTY%20IT    TECHM     1.43
2  NIFTY%20IT  MPHASIS     0.67
3  NIFTY%20IT  COFORGE     0.36
4  NIFTY%20IT      TCS     0.26

In [ ]:
from backend_handlers.record_feeders.market_positions.market_postion_executor import get_market_positions

df =get_market_positions()

In [6]:
df.head()

        index      symbol  pChange        date
0  NIFTY%2050  HINDUNILVR     4.72  2026-04-19
1  NIFTY%2050    JSWSTEEL     2.20  2026-04-19
2  NIFTY%2050   NESTLEIND     2.20  2026-04-19
3  NIFTY%2050  APOLLOHOSP     2.08  2026-04-19
4  NIFTY%2050   POWERGRID     1.89  2026-04-19

In [80]:

cur.execute("""
            CREATE TABLE IF NOT EXISTS top_gainers (
                sector VARCHAR(255),
                company VARCHAR(255),
                pCHANGE FLOAT,
                date DATE
            )
            """)

In [8]:
from backend_handlers.database_utilities.table_creators import create 

create()

In [24]:
from backend_handlers.record_feeders.feed_top_gainers import feed_gainers

feed_gainers()

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
       sector     company  pCHANGE        date
0  NIFTY%2050       TRENT     3.86  2026-04-20
1  NIFTY%2050    JSWSTEEL     2.62  2026-04-20
2  NIFTY%2050        SBIN     2.49  2026-04-20
3  NIFTY%2050    ADANIENT     2.47  2026-04-20
4  NIFTY%2050  ASIANPAINT     1.91  2026-04-20
Inserted 135 rows into top_gainers

In [25]:
from backend_handlers.record_feeders.feed_news import feed_news

feed_news(company_slug='reliance-industries', keywords=["reliance", "jio", "ril"], ticker="RELIANCE.NS")

Scraping page 1 - found 8 articles
Scraping page 2 - found 26 articles
Scraping page 3 - found 26 articles
Total collected: 7
Fetched 1 entries from Moneycontrol
Fetched 50 entries from Economic Times
Fetched 35 entries from LiveMint
Fetched 0 entries from Business Standard
                company                                              title  \
38  reliance-industries  India Stocks Soar: Global Optimism Lifts Marke...
35  reliance-industries  RIL shares drop 5% in 2 sessions: Why the stoc...
22  reliance-industries  Stocks To Watch Today: HDFC Bank, Yes Bank, IC...
33  reliance-industries  Reliance Q4 Results Date: RIL Plans FY26 Divid...
21  reliance-industries  Stocks to Watch for April 20: HDFC Bank, ICICI...

                                                  url  year  month  day
38  https://news.google.com/rss/articles/CBMi0AFBV...  2026      4   15
35  https://news.google.com/rss/articles/CBMizwFBV...  2026      4    7
22  https://news.google.com/rss/articles/CBMiuwFBV...  2026      4   19
33  https://news.google.com/rss/articles/CBMi2gFBV...  2026      4   19
21  https://news.google.com/rss/articles/CBMi6wFBV...  2026      4   19
Inserted 37 rows into news

In [4]:
from backend_handlers.record_feeders.feed_transcripts import feed_transcripts

feed_transcripts("RELIANCE")

Saved: transcripts/Con. Call_2026-04-19_1.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_2.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_3.pdf
Saved: transcripts/RELIANCE_Financial Result Updates_2026-04-19_4.pdf
Inserted 4 rows into transcripts_2

In [28]:
from backend_handlers.database_utilities.read_database import read_table_to_dataframe
import datetime

top_gainers_df = read_table_to_dataframe("top_gainers", "Sector = 'NIFTY%20IT'")

def read_top_gainers(sector):
    date_today = datetime.datetime.now().strftime("%Y-%m-%d")
    print(date_today)
    #2026-04-19
    condition = f"Sector = '{sector.replace(' ', '%20')}' AND date = '{date_today}'"
    
    gainers_df = read_table_to_dataframe("top_gainers", condition)
    return gainers_df

/Users/abhijit/Desktop/Stock_Project/Stock_value_pred_NSE/backend_handlers/database_utilities/read_database.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [29]:
read_top_gainers("NIFTY IT")

2026-04-20

       sector  company  pchange        date
0  NIFTY%20IT     OFSS     1.80  2026-04-20
1  NIFTY%20IT      TCS     0.12  2026-04-20
2  NIFTY%20IT    TECHM    -0.02  2026-04-20
3  NIFTY%20IT     INFY    -0.23  2026-04-20
4  NIFTY%20IT  HCLTECH    -0.37  2026-04-20

In [11]:
top_gainers_df.head()

       sector  company  pchange        date
0  NIFTY%20IT     OFSS     2.90  2026-04-19
1  NIFTY%20IT    TECHM     1.43  2026-04-19
2  NIFTY%20IT  MPHASIS     0.67  2026-04-19
3  NIFTY%20IT  COFORGE     0.36  2026-04-19
4  NIFTY%20IT      TCS     0.26  2026-04-19

In [48]:
import datetime
from datetime import timedelta
from backend_handlers.database_utilities.execute_query import execute_query_to_dataframe

def read_news_from_database(company_slug):
    
    from datetime import datetime, timedelta

    date_str = (datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d")
    query = f"""
    SELECT *
    FROM news
    WHERE company = '{company_slug}'
    AND MAKE_DATE(year, month, day) >= '{date_str}'
    """

    df = execute_query_to_dataframe(query)
    return df

In [49]:
read_news_from_database("reliance-industries")

/Users/abhijit/Desktop/Stock_Project/Stock_value_pred_NSE/backend_handlers/database_utilities/execute_query.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,id,company,title,url,year,month,day
0,5,reliance-industries,"Q4 results 2026: Infosys, HCL Tech, Reliance I...",https://www.livemint.com/market/stock-market-n...,2026,4,19
1,6,reliance-industries,10 Sensex stocks with up to 45% upside potenti...,https://economictimes.indiatimes.com/markets/s...,2026,4,19
2,7,reliance-industries,Stocks to buy under ₹100: Sumeet Bagadia recom...,https://www.livemint.com/market/stock-market-n...,2026,4,19
3,8,reliance-industries,Buy or sell: Ganesh Dongre of Anand Rathi reco...,https://www.livemint.com/market/stock-market-n...,2026,4,19
4,9,reliance-industries,Q4 results 2026 to US-Iran war: Top five trigg...,https://www.livemint.com/market/stock-market-n...,2026,4,19
...,...,...,...,...,...,...,...
56,70,reliance-industries,Reliance Industries announces board meet date ...,https://news.google.com/rss/articles/CBMijgJBV...,2026,4,17
57,71,reliance-industries,Stock Market Today: Sensex Moves Up by 124 Poi...,https://news.google.com/rss/articles/CBMi2gFBV...,2026,4,17
58,72,reliance-industries,Reliance Power Share Price Rises 0.21% After M...,https://news.google.com/rss/articles/CBMiqgFBV...,2026,4,17
59,73,reliance-industries,Stock Market Today: शेअर बाजाराची सपाट सुरुवात...,https://news.google.com/rss/articles/CBMi3wFBV...,2026,4,17
60,74,reliance-industries,Top stocks to buy today: Stock recommendations...,https://news.google.com/rss/articles/CBMikwJBV...,2026,4,17

In [64]:
import datetime
from datetime import timedelta
from backend_handlers.database_utilities.execute_query import execute_query_to_dataframe

def read_transcripts_from_database(company_slug):
    
    from datetime import datetime, timedelta

    query = f"""
    SELECT *
    FROM transcripts_2
    WHERE filepath = '{company_slug}'
    ORDER BY date DESC
    LIMIT 4
    """

    df = execute_query_to_dataframe(query)
    return df["url"].tolist()

In [65]:
read_transcripts_from_database("RELIANCE")

/Users/abhijit/Desktop/Stock_Project/Stock_value_pred_NSE/backend_handlers/database_utilities/execute_query.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

['transcripts//Con. Call_2026-04-19_1.pdf',
 'transcripts//RELIANCE_Financial Result Updates_2026-04-19_2.pdf',
 'transcripts//RELIANCE_Financial Result Updates_2026-04-19_3.pdf',
 'transcripts//RELIANCE_Financial Result Updates_2026-04-19_4.pdf']